# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b20d5e2492d086d23f12a9480acab1d957e2a892b1245e114fd2dbd80262b7448b649fc9f6639af8f2d86034759cb1cd2ab0035bec048d6f41b487deb2f70149

test:
  secret_key_base: 19265daaf342793d10c25f15414a010185d24b804171652e584675913226b2f0411a106b0c61f213658002758746b4bf3e00a279460b8a5855e4f4d4ad0b54c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
